spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_management_system?serverTimezone=GMT%2B8
    password: 171919
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
server:
  port: 8181